spring.datasource.url=jdbc:postgresql://localhost:5432/mrida
spring.datasource.username=postgres
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
checkout.receipt-prefix=ORDER-

# Razorpay (TEST for local)
razorpay.key.id=rzp_test_SkRzTw2gzwGeQO
razorpay.key.secret=EnSRmHsMNS80Gj8ukfWjils0