spring.application.name=demo

# decide profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}


#spring.application.name=demo
#
#
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.qczvwxoqxowopzfezlmo.supabase.co:5432/postgres}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:[YOUR-PASSWORD]}
#
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#
### Razorpay (use test/live keys from https://dashboard.razorpay.com/app/keys)
#razorpay.key.id=rzp_test_SkRzTw2gzwGeQO
#razorpay.key.secret=EnSRmHsMNS80Gj8ukfWjils0
#
##razorpay.key.id=${RAZORPAY_KEY_ID}
##razorpay.key.secret=${RAZORPAY_KEY_SECRET}
##razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET}
#
